# Generated by Django 5.1.6 on 2025-05-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='reel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
