# Generated by Django 5.1.6 on 2025-05-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels_management', '0002_remove_reel_thumbnail_reel_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='views',
        ),
        migrations.AddField(
            model_name='reel',
            name='hashtag',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
