# Generated by Django 5.1.6 on 2025-05-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='insurance_document',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='owner_cnic',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='registration_card',
        ),
    ]
