# Generated by Django 5.1.6 on 2025-05-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_onboarding', '0003_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Store list of image URLs or metadata as JSON', null=True),
        ),
    ]
