# Generated by Django 5.1.6 on 2025-05-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_onboarding', '0004_carlisting_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='fuel_policy',
            field=models.CharField(choices=[('Full_to_Full', 'Full to Full'), ('Prepaid', 'Prepaid')], max_length=20),
        ),
    ]
