# Generated by Django 5.1.6 on 2025-05-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_onboarding', '0005_alter_carlisting_fuel_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
